export const  superbaseUrl ='https://alrzxgvbagnrdlkjtwxm.supabase.co' 
export const superbaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFscnp4Z3ZiYWducmRsa2p0d3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTIyNzEsImV4cCI6MjA1NjMyODI3MX0.CkzuY1aOkHdlnBjIS0lj84gGsO4doUlD7Us1MUcr6Ho'
