export const  superbaseUrl ='https://sxbvfzykjehimhgpjwvq.supabase.co' 
export const superbaseAnonKey ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4YnZmenlramVoaW1oZ3Bqd3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjU4ODQsImV4cCI6MjA2OTgwMTg4NH0.P9LbLyXSSPitwzwvvtA-z-7KKAO0_WbTl1XHRn_PL3c'
